### ISSUE TITLE
Feature Request: Hide others, except when against me

### ISSUE THREAD

**Issue by Noshei** [Aireil/FlyTextFilter#1]
This plugin is great, but I'm not seeing a way to make it hide others attacks against NPC's, but still show the NPC's attacks against me.

So I want to only see everything I do, and anything done to me, and hide everything else.

**Comment by Aireil** [comment]
PRed the 3.1.0.0 version, adding the ability to hide fly texts based on target (not merged yet).
It's still very basic, so it's you vs others, I will probably improve upon this later.

**Comment by Noshei** [comment]
Quick test, this is looking good.  I did spot one issue, it looks like with just "Hide, from Others" (all items selected) that the damage from my DoTs is not being displayed.  It looks like this is the reason, in the log it is on others and from others.  Here is the log line from a DoT tick.
15:47:21.440 | INF [FlyTextFilter] Type: AutoAttack - Value1: 3120 - Value2 : 0 - Value3: 0 - Value4: 0 - From: Others - On: Others

**Comment by Aireil** [comment]
Yes, this is due to how the game works. You don't only see your DoTs, you see the cumulated DoTs value on the target (this is why ACT and FFLogs have to simulate DoTs).
This explains why the source isn't you, it's actually set as the enemy itself. The same thing happens with multiple abilities, like MCH's Flamethrower.
I could change the source if I see the auto-attack is from the npc itself, but that would affect everything working like this, and I'm not exactly sure what that entails.

What you see in the log cannot be wrong, because it's pulled directly from the game functions that create the fly texts, it's just the game being weird.

**Comment by Noshei** [comment]
I figured that might be the case, but just wanted to report what I was seeing anyways.

**Comment by Aireil** [comment]
Yep, thanks for the report 👍.
